import type { Metadata } from 'next'
//components
import Footer from '@/components/Footer/Footer'
import Header from '@/components/Header/Header';
import { Toaster } from 'sonner';
//styles
import "@/styles/global.scss";
//images
import fav from "./favicon.ico"


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header lng='En' />
        <main>
          {children}
        </main>
        <Toaster richColors closeButton />
        <Footer />
      </body>
    </html>
  )
}
