name: "Upload json to git repo"
on:
  workflow_dispatch:
jobs:
  upload_json:
    name: "Deploy to production"
    runs-on: ubuntu-latest
    env:
      TEST: TEST
    steps:
      - name: "Checkout the files"
        uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0
      - name: Get new json files
        run: |
          curl -k http://164.90.230.225/api/v1/languages/ | jq .[0] > src/app/i18n/locales/en/translation.json
          curl -k http://164.90.230.225/api/v1/languages/ | jq .[1] > src/app/i18n/locales/ua/translation.json
      - name: Commit json files to repo
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor}}@users.noreply.github.com'
          #git remote set-url origin https://${{ secrets.GIT_USER }}:${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }}
          git add src/app/i18n/locales/en/\*.json
          git add src/app/i18n/locales/ua/\*.json
          git commit -m "Add json files" || echo "Nothing to commit"       
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          branch: ${{ github.ref }}
          force: true
